# Project information
site_name: 'UpdateHub'
site_description: 'All your devices, always updated'

# Copyright
copyright: 'Copyright &copy; 2020 O.S. Systems'

# Repository
repo_name: 'OSSystems/updatehub-docs'
repo_url: 'https://github.com/OSSystems/updatehub-docs'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'img/assets/favicon.ico'
  feature:
    tabs: true

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/OSSystems'
    - type: 'twitter'
      link: 'https://twitter.com/OSSystemsNews?s=20'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/ossystems'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# Navigation
nav:
  - Introduction: index.md
  - What is UpdateHub: what-is-updatehub.md
  - Quick starting with Raspberry Pi 3: quick-starting-with-raspberrypi3.md
  - FAQ: faq/faq-questions.md
  - Using UpdateHub Cloud: 
    - UpdateHub Cloud dashboard: updatehub-cloud/dashboard.md
    - Managing a Product: updatehub-cloud/product.md
    - Handling a Device: updatehub-cloud/device.md
    - Package and Rollout: updatehub-cloud/package-rollout.md
    - Your menu account: updatehub-cloud/menu.md
  - Integrating with Yocto Project:
    - Yocto Project guide: yocto-project/yocto-project-guide.md
    - Yocto Project reference: yocto-project/yocto-project-reference.md
    - Glossary of variables: yocto-project/glossary.md